version: "3"

services: 
     web:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /vueapp/node_modules
            - .:/vueapp
        ports: 
            - "3000:3000"
                      
        